FROM node:20-alpine AS deps
WORKDIR /repo
COPY package.json package-lock.json ./
COPY docs/docusaurus/package.json docs/docusaurus/package.json
RUN npm ci

FROM node:20-alpine AS build
WORKDIR /repo
COPY --from=deps /repo/node_modules ./node_modules
COPY . .
RUN npm -w docs/docusaurus run build

FROM nginx:1.27-alpine AS runner
WORKDIR /usr/share/nginx/html
COPY --from=build /repo/docs/docusaurus/build ./
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
